@baseUrl = http://localhost:5023

GET {{baseUrl}}/games

###
GET {{baseUrl}}/games/1

###
POST {{baseUrl}}/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids & Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

###
PUT {{baseUrl}}/games/4
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 9.99,
    "releaseDate": "1991-02-01"
}

###
DELETE {{baseUrl}}/games/2